@echo off
setlocal
set SUPABASE_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYWZraXp0b3FrcnZzYWd2YWN6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDM2MTQ0MiwiZXhwIjoyMTA1OTM3NDQyfQ.5uEYH1c7dWMyxuiICra3QYtv6dlN4taK1gBnzE4Ae_A
echo Deploying health function...
call npx supabase functions deploy health --project-ref pfafkiztoqkrvsagvacz
echo Deploying products function...
call npx supabase functions deploy products --project-ref pfafkiztoqkrvsagvacz
echo Deploying categories function...
call npx supabase functions deploy categories --project-ref pfafkiztoqkrvsagvacz
echo Deploying bookings function...
call npx supabase functions deploy bookings --project-ref pfafkiztoqkrvsagvacz
echo Deploying auth function...
call npx supabase functions deploy auth --project-ref pfafkiztoqkrvsagvacz
echo Deploying settings function...
call npx supabase functions deploy settings --project-ref pfafkiztoqkrvsagvacz
echo Deploying users function...
call npx supabase functions deploy users --project-ref pfafkiztoqkrvsagvacz
echo Deploying payments function...
call npx supabase functions deploy payments --project-ref pfafkiztoqkrvsagvacz
echo Deploying reviews function...
call npx supabase functions deploy reviews --project-ref pfafkiztoqkrvsagvacz
echo All functions deployed!
endlocal
pause
